name: Build & Deploy
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }} 
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}  
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            git clone https://github.com/zkfairdomains/fns-metadata-service.git 
            cd fns-metadata-service/ 
            git pull origin
            corepack enable
            yarn install
            yarn build
            pm2 restart fns-metadata-service
            echo 'Deployment successful...' 
 
